import styles from '../styles/Home.module.css'
import Head from 'next/head'

export default function Login() {
    return (
      <div className={styles.login_container}>
        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>

        </main>
      </div>
    )
  }