import styles from '../styles/Home.module.css'
import Head from 'next/head'

export default function singup() {
    return (
      <div className={styles.signup_container}>
        <Head>
          <title>singup</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  

      </div>
    )
  }